### ISSUE TITLE
Use orElseGet() instead of orElse() when composing ConfigurationSources

### ISSUE THREAD

**Issue by writeoncereadmany** [unruly/java-config-fallback#2]
Currently, when composing ConfigurationSources, we use orElse:

default ConfigurationSource or(ConfigurationSource source) {
    return (key) -> Optional
       .ofNullable(this.get(key))
       .orElse(source.get(key));
}

But orElse() requires the alternate to be evaluated regardless, meaning we'll continue telescoping down to the next ConfigurationSource even if this one had a value.

Fix:

default ConfigurationSource or(ConfigurationSource source) {
    return (key) -> Optional
       .ofNullable(this.get(key))
       .orElseGet(() -> source.get(key));
}

By using a Supplier lambda, now we'll only evaluate the next source if this source fails.

**Comment by mrwilson** [comment]
Closed in b756d314
